---
base::packages_hash_debian:
  htop:
    ensure: latest
  iftop:
    {}
  augeas-tools:
    {}
  vim:
    {}
  sysstat:
    {}
  zsh:
    {}
  mc:
    {}
# curl:
#   {}
  sudo:
    {}
  screen:
    {}
  grc:
    {}
  r10k:
    provider: gem
  jq:
    {}


filebeat::prospectors:
  syslogs:
    paths:
      - '/var/log/auth.log'
      - '/var/log/syslog'
    doc_type: 'syslog'
