
# installs from the puppet forge
mod 'puppetlabs/apt'
mod "puppetlabs/stdlib"

# installs from git
mod 'role_elasticsearch',
:git => 'https://github.com/naturalis/puppet-role_elasticsearch'

mod 'role_logstash',
:git => 'https://github.com/naturalis/puppet-role_logstash'
