# Installs from the puppet forge
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "puppetlabs/vcsrepo"
mod "puppetlabs/rabbitmq"
mod "puppetlabs/tftp"
mod "puppetlabs/concat"
mod "puppetlabs-xinetd"
mod "puppetlabs-inifile"
mod "ispavailability/file_concat"
#mod "pdxcat/collectd"
mod "maestrodev/wget"
#mod "stahnma/epel"
mod "puppetlabs/git"

mod "saz/timezone"
mod "stm/debconf" # required by saz/timezone

mod "meltwater/facts"
mod "razorsedge/snmp"
mod "saz/rsyslog"
mod "arioch/redis"
mod "yelp/uchiwa"
mod "nanliu/staging"
#mod "torrancew/cron"
#mod "gbrown/yumrepos"
#mod "joshbeard/display"

# Installs from git
mod 'base',
:git => 'https://github.com/rudibroekhuizen/puppet-base'

mod 'role_base',
:git => 'https://github.com/rudibroekhuizen/puppet-role_base'

mod 'oracle_java',
:git => 'https://github.com/antoineco/aco-oracle_java'

mod 'elasticsearch',
:git => 'https://github.com/elastic/puppet-elasticsearch',
:ref => '0.15.1'

mod 'role_elasticsearch',
:git => 'https://github.com/rudibroekhuizen/puppet-role_elasticsearch'

mod 'logstash',
:git => 'https://github.com/elastic/puppet-logstash',
:ref => '5.0.3'

mod 'role_logstash',
:git => 'https://github.com/rudibroekhuizen/puppet-role_logstash'
#:ref => 'develop'

#mod 'role_collectd',
#:git => 'https://github.com/rudibroekhuizen/puppet-role_collectd'
#:ref => 'develop'

mod 'role_snmp',
:git => 'https://github.com/naturalis/puppet-role_snmp'

mod 'role_test',
:git => 'https://github.com/rudibroekhuizen/puppet-role_test'

mod 'archive',
:git => 'https://github.com/voxpupuli/puppet-archive'
#:git => 'https://github.com/camptocamp/puppet-archive'

mod 'sqlplus',
:git => 'https://github.com/naturalis/puppet-sqlplus'

#mod 'sensu',
#:git => 'https://github.com/sensu/sensu-puppet'

#mod 'role_sensu',
#:git => 'https://github.com/rudibroekhuizen/puppet-role_sensu',
#:ref => 'develop'

mod 'burp',
:git => 'https://github.com/rudibroekhuizen/puppet-burp'

mod 'role_burp',
:git => 'https://github.com/rudibroekhuizen/puppet-role_burp'

mod 'role_rsyslog',
:git => 'https://github.com/naturalis/puppet-role_rsyslog'

mod 'role_cron',
:git => 'https://github.com/rudibroekhuizen/puppet-role_cron'

#mod 'hammer_cli_foreman',
#:git => 'https://github.com/rudibroekhuizen/puppet-hammer_cli_foreman'

mod 'kibana',
:git => 'https://github.com/rudibroekhuizen/puppet-kibana'

mod 'kibana4',
:git => 'https://github.com/lesaux/puppet-kibana4'

mod 'role_tftp',
:git => 'https://github.com/rudibroekhuizen/puppet-role_tftp'

mod 'logrotate',
:git => 'https://github.com/yo61/puppet-logrotate',
:ref => 'v1.3.0'

mod 'scp',
:git => 'https://github.com/GeoffWilliams/puppet_scp',
:ref => 'v0.1.0'

mod 'backhub',
:git => 'https://github.com/rudibroekhuizen/puppet-backhub',
:ref => 'v0.1.1'

mod 'nginx',
:git => 'https://github.com/jfryman/puppet-nginx',
:ref => 'v0.2.7'

mod 'datacat',
:git => 'https://github.com/richardc/puppet-datacat',
:ref => '0.6.2'

mod 'httpauth',
:git => 'https://github.com/jamtur01/jamtur01-httpauth',
:ref => 'v0.0.2'

mod 'mysql',
:git => 'https://github.com/puppetlabs/puppetlabs-mysql',
:ref => '3.9.0'

mod 'role_mysql',
:git => 'https://github.com/naturalis/puppet-role_mysql'

mod 'filebeat',
:git => 'https://github.com/pcfens/puppet-filebeat',
:ref => 'v0.10.2'

mod 'openvpn_client',
:git => 'https://github.com/thejandroman/puppet-openvpn_client'

mod 'role_openvpn',
:git => 'https://github.com/naturalis/puppet-role_openvpn'

mod 'python',
:git => 'https://github.com/stankevich/puppet-python'

mod 'role_postgresql',
:git => 'https://github.com/rudibroekhuizen/puppet-role_postgresql'

mod 'postgresql',
:git => 'https://github.com/puppetlabs/puppetlabs-postgresql'

mod 'apache',
:git => 'https://github.com/puppetlabs/puppetlabs-apache'

mod 'php',
:git => 'https://github.com/voxpupuli/puppet-php',
:ref => '380273f'

mod 'role_php',
:git => 'https://github.com/rudibroekhuizen/puppet-role_php'

mod 'role_apache',
:git => 'https://github.com/rudibroekhuizen/puppet-role_apache'

#mod 'certbot',
#:git => 'https://github.com/danzilio/puppet-letsencrypt',
#:ref => 'certbot2'

mod 'letsencrypt',
:git => 'https://github.com/voxpupuli/puppet-letsencrypt'

mod 'drush',
:git => 'https://github.com/pcfens/puppet-drush',
:ref => 'remove_composer_dependency'

mod 'docker',
:git => 'https://github.com/garethr/garethr-docker'

# For kibana5
mod 'yamlfile',
:git => 'https://github.com/reidmv/puppet-module-yamlfile'
