# Installs from the puppet forge
mod "puppetlabs/apt"
mod "puppetlabs/stdlib"
mod "ispavailability/file_concat"
mod "elasticsearch/elasticsearch"
mod "elasticsearch/logstash"
mod "pdxcat/collectd"
mod "maestrodev/wget"
mod "stahnma/epel"
mod "puppetlabs/git"
mod "saz/timezone"

# Installs from git
mod 'base',
:git => 'https://github.com/rudibroekhuizen/puppet-base'

mod 'role_base',
:git => 'https://github.com/rudibroekhuizen/puppet-role_base'

mod 'role_elasticsearch',
:git => 'https://github.com/naturalis/puppet-role_elasticsearch'

mod 'role_logstash',
:git => 'https://github.com/naturalis/puppet-role_logstash'

mod 'role_collectd',
:git => 'https://github.com/rudibroekhuizen/puppet-role_collectd'

mod 'sqlplus',
:git => 'https://github.com/rudibroekhuizen/puppet-sqlplus'

mod 'role_sqlplus',
:git => 'https://github.com/rudibroekhuizen/puppet-role_sqlplus'
